build:
  nodes:
    analysis:
      filter:
        paths:
          - "src/"
        excluded_paths:
          - "tests/"
        dependency_paths:
          - "vendor/"
      tests:
        override:
          - php-scrutinizer-run
  environment:
    php:
      version: 7.2
