build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
  environment:
    php:
      version: 7.2
filter:
  paths:
    - "src/"
  excluded_paths:
    - "tests/"
  dependency_paths:
    - "vendor/"
