language: php

php:
  - 7
  - 7.1

before_script:
  - composer self-update
  - composer install --no-progress --no-interaction --prefer-source

script:
 - mkdir -p build/logs
 - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

matrix:
  fast_finish: true
